### ISSUE TITLE
Cannot remove Actors or Joints from Scene

### ISSUE THREAD

**Issue by AnderT** [stilldesign/PhysX.Net#19]
Hi Chad,

How are you going? All good I hope ( :

I am having a bit of a problem removing Actors and Joints from my Scene. Using Scene.RemoveActor removes the Physics and Scene from the Actor, but leaves the Actor in Scene.Actors. The Actor is not showing as disposed. If I then call Dispose on the actor I get a System.AccessViolationException.

When I call Dispose on joints they do not get removed from Scene.Joints, but they do show as disposed when I look at the objects.

I am tracking the live Actors and Joints with my own lists, so my simulation is working, but it slows down severely as the number of Actors and Joints builds up in the scene.

I am sure I am doing something wrong, so any help would be very much appreciated.

Cheers,

Ander

**Comment by stilldesign** [comment]
Hey,
I've been super busy with work lately so I've only had a quick look at this one - but you're right, there does appear to some issues around using removing/disposing of actors.

Calling Scene.RemoveActor() does nothing more than call the unmanaged equivalent (PxScene::removeActor) and will leave the actor on the managed tracking ObjectTable class and in any List<> that keep track of it. I don't make use of the function internally, so perhaps I should just remove it to avoid confusion.
To remove an actor, call Dispose on it.

Calling Dispose on Joints should work... you say they don't get removed from Scene.Joints, but there isn't a property in Scene called Joints...

It's been a few days since you asked, so you may of solved this and moved forward, if it's still a problem let me know

**Comment by AnderT** [comment]
Hi Chad,
Still having problems, I started re-creating the scene every time it became empty, but it causes a massive memory leak that I cannot seem to get under control. If I just call Dispose on my actors I get;

![image](https://cloud.githubusercontent.com/assets/11612389/11336017/d42594ea-9235-11e5-8af1-6164848eed1b.png)

And if I just leave them, I get the slowdown as they build-up.

I am not sure what to do, I have not upgraded to the latest build as I will have to do a lot of work to change over to System.Numerics, maybe I need to bite the bullet.

Any thoughts?

Cheers,

Ander

**Comment by stilldesign** [comment]
That's a tricky one, to work on this, I'll have to write up a test app to try and reproduce this.
Roughly what's the scene look like when these errors occur (how many actors, what types of shapes or joints do you have)?

Usually if you get AccessViolationException when calling Dispose on an Actor (or anything in PhysX.Net) it's simply because the actual PhysX object inside has been disposed by another bit of code.
Are you calling RemoveActor() at any time?

When you say you're getting memory leaks, do you mean objects are hanging around indefinitely without getting deleted or cleaned up and your process size is growing and growing? If so, I'd need to try and see which objects are remaining around by using ANTS profiler tool.

**Comment by AnderT** [comment]
Hi Chad,

Thanks for helping with this : )

I put a very minimal test together, Button click sets up the scene with the ground actor as the only actor in the scene and calls simulate.

The next button click calls dispose on the ground actor, causing an AccesViolationException.
![image](https://cloud.githubusercontent.com/assets/11612389/11422744/a315d914-9492-11e5-9686-ae36bbb7cf9b.png)

I hope you can see what I am doing wrong.

Cheers again.

Ander

**Comment by stilldesign** [comment]
Hey,
I wrote out an app using your code and version 0.2.0 of the PhysX.Net nuget package (which I assume is the version you're using) and I was able to create the scene and actor, simulate and dispose of the actor successfully. I'm just on lunch at work atm, so I'll give it a closer look when I get home.

Are you able to zip your test app, with the code and exe inside it? so I can try run it on my machine to see if it also errors

**Comment by AnderT** [comment]
Hi Chad,
I am using a different version of the PhysX.net DLL dated 14/09/2014, if I remember correctly you sent it to me when I was having problems reading data from a constraint. If I change to the one dated 12/07/2014 then it works for the test, but my project no longer works.

I think that I should update my project to the latest version and see how that goes.

Thanks again for all your help, it is very much appreciated : )

Ander

**Comment by AnderT** [comment]
Hi Chad,

I have updated to the newest build and now all is working with dispose on the actor : )
