### ISSUE TITLE
It will support .netCore in future?

### ISSUE THREAD

**Issue by yhr28** [stilldesign/PhysX.Net#38]

**Comment by stilldesign** [comment]
Would love to, but it looks like C++/CLI support for .NET Core is not available at the moment - https://github.com/dotnet/coreclr/issues/659

**Comment by yhr28** [comment]
Thanks!

**Comment by daguang080710** [comment]
.Net Core support P/Invoke mode.Can you change yours to use P/Invoke mode?

**Comment by Viagi** [comment]
This looks great! My project server use .net core, which I hope will be supported in the future

**Comment by FlameskyDexive** [comment]
wow, what I expect is that phyx will run in net core, cause net core is so powerful for C# server development, hope you will support netcore

**Comment by qq362946** [comment]
netcore is so powerful for c# server development, I hope you will support netcore

**Comment by stilldesign** [comment]
As @daguang080710 says, creating a version which only uses P/Invoke instead of C++/CLI would be the only way to go at this stage. Unfortunately that would be quite a large amount of work, I just don't know if I'd be able to find the time :'(

I'd take a different approach though, I'd write something which generated the method signatures off the actual .h header files (or the documentation files).

**Comment by yhr28** [comment]
> As @daguang080710 says, creating a version which only uses P/Invoke instead of C++/CLI would be the only way to go at this stage. Unfortunately that would be quite a large amount of work, I just don't know if I'd be able to find the time :'(
> 
> I'd take a different approach though, I'd write something which generated the method signatures off the actual .h header files (or the documentation files).

Thanks!!!

**Comment by kersk** [comment]
@stilldesign I haven't used it yet myself, but something like this? https://github.com/mono/CppSharp
