### ISSUE TITLE
Multiple instances in the same process

### ISSUE THREAD

**Issue by Mockarutan** [stilldesign/PhysX.Net#39]
I'm working in a "by default" networked game engine where both server and client are always running. And in dev mode both the server and client is running though the same process. For obvious reasons I want to run one PhysX instance on the server and one on the client, both in dev mode and in normal mode. When I try to initialize a second foundation for the client I get the "Foundation can only be initalized once" error. Now, is there an inherent limitation in PhysX for this or is it a limitation of this wrapper? I have not dugg thought the code or documentation enough to know, I only found the static _Initialized variable in Foundation.h. But I thought it might be a good idea to ask instead of experiment by building the dlls myself with non static initialize.

Thanks!

**Comment by stilldesign** [comment]
Is it possible to just create a second `Physics` instance, but only the one `Foundation` class?

**Comment by Mockarutan** [comment]
Right, did not think of that. Using one Foundation got this instead then: "The physics core object has already been instantiated. Check Physics.Instantiated before calling this ctor."
But one static Foundation and one static Physics object, with multiple scenes was allowed. Going to see if this actually works for my use case. I assume parallell scenes does not share anything that will block this though.

Thanks for the answer!

**Comment by stilldesign** [comment]
Ah right, I can't remember why having multiple Foundation or Physics instances isn't allowed in PhysX, it's been years since I wrote that bit :P I might go back and review that now.

I've never tried creating multiple `Scene` instances, so I'm not sure how well it will work. PhysX itself does indeed support it, but I've never tested it in the wrapper as I've just never needed to for my projects. I should probably write some tests around this.

One slightly more drastic approach to running multiple Foundation/Physics instances might be to create 2 `AppDomain` instances and run PhysX in each one, that way they're completely separated. Though I've never tried this either.
