### ISSUE TITLE
Net6 please ♪

### ISSUE THREAD

**Issue by oz01** [stilldesign/PhysX.Net#49]

**Comment by stilldesign** [comment]
Hi, I've updated it to .NET 6.0, PhysX 4.1.2 and VC143 runtime: https://github.com/stilldesign/PhysX.Net/tree/412-net6
I think might be a problem with PhysXDevice64.dll being VC142 though. So atm you might need 2 runtimes installed, which is less than ideal. I don't think I can do much because the source for that dll isn't available.
